window.PRAGMAP_CONFIG = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  STORAGE_BUCKET: 'spot-images',
  ENABLE_PASSWORD_LOGIN: true,
  ENABLE_MAGIC_LINK: false,
  DEFAULT_LOGIN_EMAIL: '',
  GITHUB_PAGES_BASE: '',
};
